"""
utils/drive_image_service.py

Google Drive Image Service for SentimentMapApp Backend.

Transparently serves images from Google Drive using the same API endpoint
as local storage (/api/images/<location>/<filename>). The frontend code
requires zero changes.

Architecture:
  1. At startup, load drive_mapping.json (pre-generated by drive_scan.py)
     which maps { "Location Name": { "1.jpg": "DRIVE_FILE_ID", ... } }
  2. On each /api/images request, look up the Drive file ID from the mapping
  3. Check the in-memory cache — return bytes directly if cached
  4. If cache miss, download from Drive API and cache the result
  5. Respond with image bytes + correct MIME type

Result: First load per image takes ~1-2s (Drive download).
        Subsequent loads are instant (in-memory cache).
"""

import io
import json
import logging
import time
from pathlib import Path
from threading import Lock, Thread
from typing import Optional, Tuple

logger = logging.getLogger(__name__)

# ── Globals ────────────────────────────────────────────────────────────────────
_cache = None


# ── Drive API Service ──────────────────────────────────────────────────────────
# Using thread-local storage so each Flask worker thread gets its OWN Drive
# service instance with its own HTTP connection. This prevents SSL corruption
# that occurs when multiple threads share a single connection pool.

import threading as _threading
_thread_local = _threading.local()
_credentials_path_ref = [None]  # stores the path so threads can self-initialize


def _get_drive_service(credentials_path: str):
    """
    Get a thread-local Google Drive API v3 service instance.
    Each thread creates its own connection — fully thread-safe.
    """
    # Store credentials path for lazy thread initialization
    if credentials_path:
        _credentials_path_ref[0] = credentials_path

    stored_path = credentials_path or _credentials_path_ref[0]

    # Check if this thread already has a service
    if getattr(_thread_local, 'drive_service', None) is not None:
        return _thread_local.drive_service

    if not stored_path or not Path(stored_path).exists():
        logger.error(
            f"[Drive] Service account credentials not found at: '{stored_path}'. "
            f"Set GOOGLE_APPLICATION_CREDENTIALS in your .env file."
        )
        return None

    try:
        from google.oauth2 import service_account
        from googleapiclient.discovery import build

        creds = service_account.Credentials.from_service_account_file(
            stored_path,
            scopes=['https://www.googleapis.com/auth/drive.readonly']
        )
        service = build('drive', 'v3', credentials=creds, cache_discovery=False)
        _thread_local.drive_service = service
        logger.info(f"✅ [Drive] Service initialized for thread {_threading.current_thread().name}")
        return service
    except Exception as e:
        logger.error(f"❌ [Drive] Failed to initialize Drive service: {e}")
        return None


# ── In-Memory Image Cache ──────────────────────────────────────────────────────

class _ImageCache:
    """
    Simple TTL-based in-memory cache for image bytes.

    - Keys are 'LocationName/filename.jpg'
    - Values are (image_bytes, mime_type, timestamp)
    - Evicts the oldest item when max_items is exceeded
    - Items expire after ttl_seconds (default 1 hour)
    """

    def __init__(self, max_items: int = 300, ttl_seconds: int = 3600):
        self._store: dict = {}
        self._lock = Lock()
        self.max_items = max_items
        self.ttl = ttl_seconds

    def get(self, key: str) -> Optional[Tuple[bytes, str]]:
        with self._lock:
            entry = self._store.get(key)
            if entry is None:
                return None
            data, mime, ts = entry
            if time.time() - ts > self.ttl:
                del self._store[key]
                return None
            return data, mime

    def set(self, key: str, data: bytes, mime: str):
        with self._lock:
            # Evict oldest item if cache is full
            if len(self._store) >= self.max_items:
                oldest_key = min(self._store, key=lambda k: self._store[k][2])
                del self._store[oldest_key]
                logger.debug(f"[Drive Cache] Evicted: {oldest_key}")
            self._store[key] = (data, mime, time.time())

    def size(self) -> int:
        with self._lock:
            return len(self._store)

    def total_bytes(self) -> int:
        with self._lock:
            return sum(len(v[0]) for v in self._store.values())


def _get_cache(max_items: int = 300, ttl: int = 3600) -> _ImageCache:
    """Return the singleton cache instance, creating it if needed."""
    global _cache
    if _cache is None:
        _cache = _ImageCache(max_items=max_items, ttl_seconds=ttl)
        logger.info(
            f"[Drive Cache] Initialized (max_items={max_items}, ttl={ttl}s)"
        )
    return _cache


# ── Drive Mapping ──────────────────────────────────────────────────────────────

def load_drive_mapping(mapping_file: Path) -> dict:
    """
    Load the pre-generated Drive folder structure from drive_mapping.json.

    Expected format:
      {
        "Bentota Beach": {
          "0.jpg": "1aBcDeF_DRIVE_FILE_ID",
          "1.jpg": "2GhIjKl_DRIVE_FILE_ID",
          ...
        },
        "Galle Fort": { ... },
        ...
      }

    Returns an empty dict if the file is missing or malformed.
    Run drive_scan.py to generate this file.
    """
    if not mapping_file.exists():
        logger.warning(
            f"⚠️  [Drive] Mapping file not found: {mapping_file}. "
            f"Run: python drive_scan.py --folder-id YOUR_FOLDER_ID "
            f"--credentials path/to/key.json"
        )
        return {}
    try:
        with open(mapping_file, 'r', encoding='utf-8') as f:
            mapping = json.load(f)
        location_count = len(mapping)
        file_count = sum(len(v) for v in mapping.values())
        logger.info(
            f"✅ [Drive] Mapping loaded: {location_count} locations, "
            f"{file_count} images"
        )
        return mapping
    except Exception as e:
        logger.error(f"❌ [Drive] Failed to load mapping file '{mapping_file}': {e}")
        return {}


def get_file_id(mapping: dict, location_name: str, filename: str) -> Optional[str]:
    """
    Look up a Drive file ID for a given location and filename.
    Falls back gracefully when exact match is not found:
      1. Try exact match (e.g. '1.jpg')
      2. If numeric stem: try +1 offset  (e.g. '0.jpg' → '1.jpg')
      3. If still not found: return the first numerically-sorted file in folder

    This handles the common case where local images start at 0.jpg
    but uploaded Drive images start at 1.jpg.
    """
    # Resolve location (exact, then case-insensitive)
    location_data = mapping.get(location_name)
    if location_data is None:
        for key in mapping:
            if key.lower() == location_name.lower():
                location_data = mapping[key]
                break

    if not location_data:
        logger.warning(
            f"[Drive] Location '{location_name}' not found in mapping. "
            f"Available: {list(mapping.keys())[:5]}..."
        )
        return None

    # 1. Exact match
    file_id = location_data.get(filename)
    if file_id:
        return file_id

    stem = Path(filename).stem
    ext = Path(filename).suffix

    # 2. Numeric offset fallback (0.jpg → 1.jpg, 1.jpg → 2.jpg, etc.)
    if stem.isdigit():
        offset_name = str(int(stem) + 1) + ext
        file_id = location_data.get(offset_name)
        if file_id:
            logger.debug(
                f"[Drive] Offset fallback: '{location_name}/{filename}' "
                f"→ '{offset_name}'"
            )
            return file_id

    # 3. First available file (numerically sorted)
    if location_data:
        def _sort_key(name):
            s = Path(name).stem
            return int(s) if s.isdigit() else 999999

        sorted_files = sorted(location_data.items(), key=lambda x: _sort_key(x[0]))
        if sorted_files:
            fallback_name, fallback_id = sorted_files[0]
            logger.info(
                f"[Drive] First-file fallback: '{location_name}/{filename}' "
                f"→ '{fallback_name}'"
            )
            return fallback_id

    logger.warning(
        f"[Drive] No file found for '{location_name}/{filename}'. "
        f"Available: {list(location_data.keys())[:5]}..."
    )
    return None



# ── Core: Fetch Image from Google Drive ───────────────────────────────────────
# Uses `requests` directly instead of googleapiclient's MediaIoBaseDownload.
# `requests` has thread-safe connection pooling; httplib2 does NOT.

def _get_thread_session(credentials_path: str):
    """
    Get a thread-local requests.Session with a valid OAuth2 bearer token.
    Refreshes the token automatically when it expires.
    Each thread has its own session — fully thread-safe.
    """
    import requests as _requests
    from google.oauth2 import service_account
    import google.auth.transport.requests as ga_transport

    stored_path = credentials_path or _credentials_path_ref[0]
    if not stored_path or not Path(stored_path).exists():
        logger.error(f"[Drive] Credentials not found: {stored_path}")
        return None, None

    # Load or refresh credentials per thread
    creds = getattr(_thread_local, 'creds', None)
    if creds is None:
        creds = service_account.Credentials.from_service_account_file(
            stored_path,
            scopes=['https://www.googleapis.com/auth/drive.readonly']
        )
        _thread_local.creds = creds

    # Refresh token if expired or not yet obtained
    if not creds.valid:
        try:
            transport = ga_transport.Request()
            creds.refresh(transport)
        except Exception as e:
            logger.error(f"[Drive] Token refresh failed: {e}")
            _thread_local.creds = None
            return None, None

    # Get or create the thread-local requests session
    session = getattr(_thread_local, 'req_session', None)
    if session is None:
        session = _requests.Session()
        session.headers.update({'Authorization': f'Bearer {creds.token}'})
        _thread_local.req_session = session
    else:
        # Update token in case it was refreshed
        session.headers['Authorization'] = f'Bearer {creds.token}'

    return session, creds


def fetch_image(
    credentials_path: str,
    mapping: dict,
    location_name: str,
    filename: str,
    cache_ttl: int = 3600,
    max_cache_items: int = 300,
) -> Optional[Tuple[bytes, str]]:
    """
    Fetch an image from Google Drive, with in-memory caching.

    Flow:
      1. Check in-memory cache → return immediately if hit
      2. Look up Drive file ID in the pre-loaded mapping
      3. Download via requests (thread-safe, with 30s timeout)
      4. Cache the result for future requests
      5. Return (image_bytes, mime_type)
    """
    cache_key = f"{location_name}/{filename}"
    cache = _get_cache(max_items=max_cache_items, ttl=cache_ttl)

    # ── 1. Cache check ─────────────────────────────────────────────────────────
    cached = cache.get(cache_key)
    if cached is not None:
        logger.debug(f"[Drive Cache] HIT: {cache_key}  ({cache.size()} items)")
        return cached

    logger.info(f"[Drive] Cache MISS — fetching: {cache_key}")

    # ── 2. File ID lookup ──────────────────────────────────────────────────────
    file_id = get_file_id(mapping, location_name, filename)
    if not file_id:
        return None

    # ── 3. Download via requests (thread-safe) ─────────────────────────────────
    try:
        session, creds = _get_thread_session(credentials_path)
        if session is None:
            return None

        url = f"https://www.googleapis.com/drive/v3/files/{file_id}?alt=media"
        response = session.get(url, timeout=30)

        # Token may have expired mid-request — refresh and retry once
        if response.status_code == 401:
            logger.info(f"[Drive] Token expired, refreshing for {cache_key}...")
            from google.auth.transport.requests import Request
            creds.refresh(Request())
            session.headers['Authorization'] = f'Bearer {creds.token}'
            _thread_local.req_session = None  # force new session next time
            response = session.get(url, timeout=30)

        if response.status_code != 200:
            logger.error(
                f"[Drive] ❌ HTTP {response.status_code} for '{cache_key}' "
                f"(file_id={file_id})"
            )
            return None

        image_bytes = response.content
        mime_type = response.headers.get('Content-Type', 'image/jpeg').split(';')[0]
        size_kb = len(image_bytes) // 1024

        # ── 4. Store in cache ──────────────────────────────────────────────────
        cache.set(cache_key, image_bytes, mime_type)
        logger.info(
            f"[Drive] ✅ {cache_key} | "
            f"{size_kb}KB | cache: {cache.size()} items "
            f"(~{cache.total_bytes() // 1024}KB)"
        )
        return image_bytes, mime_type

    except Exception as e:
        logger.error(f"[Drive] ❌ Failed '{cache_key}': {type(e).__name__}: {e}")
        return None


def get_cache_stats() -> dict:
    """Return current cache statistics for the /api/health endpoint."""
    if _cache is None:
        return {'items': 0, 'total_kb': 0}
    return {
        'items': _cache.size(),
        'total_kb': _cache.total_bytes() // 1024,
    }
